In [1]:
import pvmismatch
from pvmismatch.contrib.gen_coeffs import gen_two_diode

from pvlib import pvsystem, location, solarposition
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import solarpanels

In [2]:
# Step one is to create get cell parameters for the rich solar cells
rich_solar_12V_params = solarpanels.get_rich_solar_MEGA200_12V()

result, message = gen_two_diode(
    rich_solar_12V_params['I_sc_ref'],
    rich_solar_12V_params['V_oc_ref'],
    rich_solar_12V_params['I_mp_ref'],
    rich_solar_12V_params['V_mp_ref'],
    rich_solar_12V_params['N_s'],
    1,
    rich_solar_12V_params['temp_ref'])

print(result)
print(message)

(2.28618816125344e-11, 1.117455042372326e-06, 0.004267236774264931, 10.01226369025448)
 message: The iteration is not making good progress, as measured by the 
            improvement from the last ten iterations.
 success: False
  status: 5
     fun: [-1.763e-04 -6.827e-02  3.619e-03 -1.529e-10]
       x: [-2.395e+01 -6.903e+02  5.456e-02  2.139e+02]
  method: hybr
    nfev: 26
    njev: 3
    fjac: [[-7.388e-01 -3.392e-02 -6.730e-01 -1.108e-11]
           [ 6.739e-01 -4.247e-02 -7.376e-01 -6.941e-13]
           [ 3.570e-03  9.985e-01 -5.424e-02 -1.809e-08]
           [-5.686e-11 -1.806e-08  9.891e-10 -1.000e+00]]
       r: [ 1.381e+01  3.097e-12  2.485e+02 -1.763e-07 -1.439e-12
            2.725e+02  1.094e-08  5.133e-01  1.165e-07 -1.297e-15]
     qtf: [-1.656e-05  9.627e-05 -6.837e-02  1.390e-09]
